# Ko build configuration
# See: https://ko.build/configuration/

# Disable SBOM generation
sboms: none

builds:
  - id: olm-extractor
    main: ./cmd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/lburgazzoli/olm-extractor/internal/version.Version={{.Env.VERSION}}
      - -X github.com/lburgazzoli/olm-extractor/internal/version.Commit={{.Env.COMMIT}}
      - -X github.com/lburgazzoli/olm-extractor/internal/version.Date={{.Env.DATE}}

